# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: UBI Center
description: Analyzing universal basic income policies with open-source research
cover: assets/images/ubi_center_blue.jpg
logo: assets/images/ubi_center_logo_wide_white.jpg
logo_dark: assets/images/ubi_center_logo_wide_blue.jpg
favicon: assets/images/ubi_center_logo_square_blue.png
social_preview_image: assets/images/logo_wide_social_preview.png
CNAME: #add cname for website to be created

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: TheUBICenter
facebook: UBICenter
github: UBICenter
instagram: ubicenter
# mailchimp-list: 
# Disqus
disqus: False
disqus_shortname: ubicenter

# Google Analytics
google_analytics: UA-138885251-1 # replace with your GA tracking identifier

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for building master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: UBICenter
repo: ubicenter.org
branch: master
relative_source: ../ubicenter.org/
destination: ./_site
production_url:  https://ubicenter.org/
source_url:  https://github.com/ubicenter/ubicenter.org/

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
